-- Rollback de la migration initiale

DROP TABLE IF EXISTS es_version_machine CASCADE;
DROP TABLE IF EXISTS es_version CASCADE;
DROP TABLE IF EXISTS es_state_index CASCADE;
DROP TABLE IF EXISTS es_state CASCADE;
DROP TABLE IF EXISTS es_action_index CASCADE;
DROP TABLE IF EXISTS es_action CASCADE;
DROP TABLE IF EXISTS es_sms_send CASCADE;
DROP TABLE IF EXISTS es_phone CASCADE;
DROP TABLE IF EXISTS es_cle_machine CASCADE;
DROP TABLE IF EXISTS es_user CASCADE;
DROP TABLE IF EXISTS es_machine CASCADE;
DROP TABLE IF EXISTS es_data_index CASCADE;




